config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  root "pages#index"
  get  '/login', to: 'sessions#new'
  post  '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :events, only: [:new, :create, :show, :index]
  resources :invitations, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, foreign_key: :creator_id, class_name: 'User'
  has_many :invitations, foreign_key: :attended_event_id
  has_many :attendees, through: :invitations, source: :attendee
  scope :past, -> { where('date < ?', DateTime.now) }
  scope :upcoming, -> { where('date >= ?', DateTime.now) }
  # def self.created_before(time)
  #   where('date <= ?', time)
  # end

  # def self.upcoming_events(time)
  #   where('date > ?', time)
  # end
  validates :date, presence: true
  validates :description, presence: true, length: { maximum: 300 }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: :creator_id
  has_many :invitations, foreign_key: :attendee_id
  has_many :attended_events, through: :invitations, source: :attended_event
  validates :name, presence: true, uniqueness: true, length: { minimum: 6 }
  validates :email, presence: true, uniqueness: true, length: { minimum: 11 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @past = Event.all.past.order('date desc')
    @upcoming = Event.all.upcoming.order('date asc')
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def new
    @event = Event.new
  end

  def show
    @invitation = current_user.invitations.build
    @event = Event.find(params[:id])
    @attendee = @event.attendees
  end

  private

  def event_params
    params.require(:event).permit(:date, :description)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def new
    @invitation = Invitation.new
  end

  def create
    @invitation = current_user.invitations.build(invitation_params)
    if @invitation.save
      redirect_to current_user
    else
      render :new
    end
  end

  private

  def invitation_params
    params.require(:invitation).permit(:attendee_id, :attended_event_id, :host_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include SessionsHelper

  def index; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(name: params[:session][:name])
    log_in @user if @user
    redirect_to root_url
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  def new
    @user = User.new
  end

  def show
    @invitation = current_user.invitations.build
    @user = User.find(params[:id])
    @past_user = current_user.events.past.order('date desc')
    @upcoming_user = current_user.events.upcoming.order('date asc')
    @past = Event.all.past.order('date desc')
    @upcoming = Event.all.upcoming.order('date asc')
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in?
    if current_user.nil?
      false
    else
      true
    end
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    current_user ||= User.find_by(id: session[:user_id])
    current_user
  end
end

app/views/events/index.html.erb
<div class = "flex">
  <fieldset class="field-danger">
  <div>
    <h1 class="danger">Past</h1>
    <% @past.each do | event | %>
      <strong><%= event.creator.name %>: </strong>
      <p><%= event.date %></p>
      <%= link_to event do %>
        <p><%= event.description %></p>
      <% end %>
    <% end %>
  </div>
</fieldset>
  <fieldset class="field">
  <div>
    <h1 class="warm">Upcoming</h1>
    <% @upcoming.each do | event | %>
      <strong><%= event.creator.name %>: </strong>
      <p><%= event.date %></p>
      <%= link_to event do %>
        <p><%= event.description %></p>
      <% end %>
    <% end %>
  </div>
</fieldset>
</div>

app/views/events/new.html.erb
<div class="text-input">
<%= form_for @event do |f| %> 
Date: <%= f.date_field :date, placeholder: "Your event's date", class: 'set' %><br><br>
Description: <%= f.text_area :description, placeholder: 'Your description', class: 'text-area', cols: 23, rows: 10 %><br><br>
<%= f.submit class: 'event-button' %>
<% end %> 

</div>

app/views/events/show.html.erb
<p>
  <strong>Host</strong>
  <%= @event.creator.name %> <br> <br>
  <strong>Date:</strong>
  <%= @event.date %><br><br>
  <strong>Description:</strong>
  <%= @event.description %>
</p>
<br>

<%= render 'shared/invite_form'%>
<br>
<h1>Invited people: </h1><br>
<% @attendee.each do  | invitation | %>
  <%= invitation.name %><br><br>
<% end %>

app/views/invitations/new.html.erb
<%= form_for(@invitation) do |f| %>
	<%= f.hidden_field :host_id, value: current_user.id %>
	<%= f.hidden_field :attended_event_id, value: current_user.events[0][:id] %>
	User: <%= f.text_field :attendee_id, placeholder: "Please enter the user's ID" %><br><br>
	<%= f.submit 'Invite' %>
	<p><%= current_user.events[0][:id] %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class = "flex">
      <%= link_to root_path do %>
          <h1>Home</h1>
      <% end %>

      <% if sign_in? %>
      
      <%= link_to current_user do %>
          <h2>My profile</h2>
      <% end %>
      <%= link_to new_event_path do %>
          <h2>Create event</h2>
      <% end %>
      <%= link_to events_path do %>
          <h2>Show events</h2>
      <% end %>
      <%= link_to logout_path, method: :delete do %>
      <h2>Log out</h2>
      <% end %>
      <% else %>
      <%= link_to login_path do %>
          <h2>Sign in</h2>
      <% end %>
      <%= link_to new_user_path do %>
          <h2>Sign up</h2>
      <% end %>
    <% end %>
    </nav>
    
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
   <div>
    <div class="home-page">
   <% if current_user %>
     <h1>Welcome to Events planner, <%= current_user.name %>!</h1>
   <%else %>
    </div>
     <div class="index-page">
     <h1>Welcome to Events planner</h1>
     <h4>Home where we help you plan your events and invite all your guest as you want.</h4>
     <h2>To use event planner, kindly register</h2>
    </div>
<% end %>
</div>
   

app/views/shared/_invite_form.html.erb
<%= form_for(@invitation) do |f| %>
  <% if current_user.id == @event.creator_id %>
	  <%= f.hidden_field :host_id, value: current_user.id %>
	  <%= f.hidden_field :attended_event_id, value: @event.id %>
	  User: <%= f.collection_select :attendee_id, User.all, :id, :name, placeholder: "Please enter the user's ID" %><br><br>
	  <%= f.submit 'Invite' %>
  <% end %>
<% end %>

app/views/users/new.html.erb
<div class="details">
<%= form_for @user do |f| %> 
Username: <%= f.text_field :name, placeholder: 'Your name here' %><br><br>
<div class="set-signup">
E-mail: <%= f.email_field :email, placeholder: 'example@example.com' %><br><br>
</div>
<%= f.submit %>
<% end %> 
</div>

app/views/users/show.html.erb
<div class = "flex">
  <fieldset class="field-warm">
  <div>
    <h1>Events you are hosting</h1>
    <h2 class="danger">Past</h2>
    <% @past_user.each do | event | %>
      <strong><%= event.creator.name %>: </strong>
      <p><%= event.date %></p>
      <%= link_to event do %>
        <p><%= event.description %></p>
      <% end %>
    <% end %>
    <h2 class="warm">Upcoming</h2>
    <% @upcoming_user.each do | event | %>
      <strong><%= event.creator.name %>: </strong>
      <p><%= event.date %></p>
      <%= link_to event do %>
        <p><%= event.description %></p>
      <% end %>
    <% end %>
  </div>
</fieldset>
  <fieldset class="field">
  <div>
    <h1>Events you are attending</h1>
    <h2 class="danger">Past</h2>
    <% @past.each do | event |%>
      <% if event.attendee_ids.include?(current_user.id) %>
        <strong><%= event.creator.name %>: </strong>
        <p><%= event.date %></p>
        <%= link_to event do %>
        <p><%= event.description %></p>
        <% end %>
      <% end %>
    <% end %>
    <h2 class="warm">Upcoming</h2>
    <% @upcoming.each do | event |%>
      <% if event.attendee_ids.include?(current_user.id) %>
        <strong><%= event.creator.name %>: </strong>
        <p><%= event.date %></p>
        <%= link_to event do %>
        <p><%= event.description %></p>
        <% end %>
      <% end %>
    <% end %>
  </div>
</fieldset>
</div>